management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
info:
  app:
    name: "KPIBuilder"
    description: "KPIBuilder est un module permettant de generer des statistiques dans les projets Java Spring Boot"
    java:
      version: 17
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: root
    password: password
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    